# PACKAGES antora@3.2.0-alpha.2 @antora/atlas-extension:1.0.0-alpha.1 @antora/collector-extension@1.0.0-alpha.3 @springio/antora-extensions@1.3.0 @asciidoctor/tabs@1.0.0-beta.3 @springio/asciidoctor-extensions @opendevise/antora-release-line-extension@1.0.0
#
# The purpose of this Antora playbook is to build the docs in the current branch.
antora:
  extensions:
  - '@antora/collector-extension'
  - id: '@antora/atlas-extension'
    require: '@antora/atlas-extension'
    enabled: false
  - '@springio/antora-extensions/latest-version-extension'
  - require: '@springio/antora-extensions/root-component-extension'
    root_component_name: 'micrometer'
site:
  title: Micrometer
  url: https://micrometer.io/docs/micrometer/reference/
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: ./..
    branches: HEAD
    start_path: docs
    worktrees: true
asciidoc:
  attributes:
    hide-uri-scheme: '@'
    page-pagination: ''
    tabs-sync-option: '@'
  extensions:
  - '@asciidoctor/tabs'
  - '@springio/asciidoctor-extensions'
  - '@springio/asciidoctor-extensions/include-code-extension'
  sourcemap: true
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
runtime:
  log:
    failure_level: error
ui:
  bundle:
    url: https://github.com/rwinch/antora-ui-micrometer/releases/download/latest/ui-bundle.zip
    snapshot: true

